spring.application.name=RbiBank
server.servlet.context-path=/api/v1

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rbibankdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ksumanth@999}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwtSecret=${JWT_SECRET:62d7fa220efe08d4a4a9c29723398ce88c9438e94f6c1b3001389425761f5254}

currencyApiKey=${CURRENCY_API_KEY:cur_live_bNgC61KKaZ3jneifNW3cFzCN3wJOF9a9LEsyjm3G}
exchange-rate.enabled=${EXCHANGE_RATE_ENABLED:true}

logging.level.org.springframework.security=DEBUG
